### PR TITLE
Fixed problem with determining mime-type of asset content

### PR DESCRIPTION
**Pull request by o**
Hi Justin, 

Problem : Asset files not serving correctly (ex. jQuery), cause PHP adds error lines to asset files (I'm on OSX/ PHP 5.3.8 w/ XDebug) :

<code>Strict standards: Only variables should be passed by reference in /genghis.php on line ...</code>

This little fix solves problem with this error.

Before : http://img198.imageshack.us/img198/5671/screenshot20111020at111.png
After : http://img692.imageshack.us/img692/5671/screenshot20111020at111.png

### CODE REVIEW

**Comment by bobthecow** [comment]
Thanks!

Also, did you manually update `genghis.php`? I wouldn't wish that on anyone :P

**Comment by o** [comment]
Yes, i updated <code>genghis.php</code> manually. It not easy :)

**Comment by bobthecow** [comment]
I guess I never turned on `E_STRICT` on this machine. That has now been fixed as well. Thank you for catching this.

**Comment by bobthecow** [comment]
For next time, there's a Rakefile to handle that for you.

```
rake build            # Compile Genghis
rake build:css        # Compile Genghis CSS assets
rake build:js         # Compile Genghis JavaScript assets
rake clean            # Remove any temporary products.
rake clobber          # Remove any generated file.
rake clobber_package  # Remove package products
rake package          # Build all the packages
rake repackage        # Force a rebuild of the package files
```

I usually use `rake clobber build package`, but you can leave off the `package` task since all you need to do is regenerate the file.

**Comment by o** [comment]
Thanks for the explanation man,

I'm not familiar with rake. For dirty solution, i need to play with <code>genghis.php</code> actually. 

Cheers!

**Pull request merged**
