### PR TITLE
Use normal browser behaviour when navigating links if ctrl or shift key was pressed

### PR DESCRIPTION
**Pull request by craigerm**
#128

### CODE REVIEW

**Comment by bobthecow** [comment]
Good call. These should include `e.metaKey` as well (for the Macs).

I've updated the Bootstrap submodule, so hopefully Travis will like us again.

**Comment by craigerm** [comment]
Ok awesome - I'll add that.  Hmm, I probably should move the check into a utility function so we don't have to update this in the different views.

I was going to mention the bootstrap issue since I couldn't get everything up and running on a different box without changing the submodule path to the TWBS repo. But I forgot  about it this morning :P

**Comment by bobthecow** [comment]
It's not like this will change all that often, so I don't know whether it's worth extracting it to a utility. Maybe invert the check so it's more compact instead?

``` js
function(e) {
  if (e.shiftKey || e.metaKey || e.ctrlKey) return;

  // ...
}
```

**Comment by bobthecow** [comment]
Thanks!

**Comment by craigerm** [comment]
Good call - that works for me. The meta key always seems to return false on my machine so I can't test the case where it's true.

Oh and I just realized I did this on my develop branch instead of a feature branch. I can send over a new pull request with a feature branch if you prefer - just lemeeknow.

Thanks!

**Comment by craigerm** [comment]
I should have refreshed before commenting :)

**Pull request merged**
