### PR TITLE
MongoDB 3.0 - store engine wiredTiger

### PR DESCRIPTION
**Pull request by ttaranto**
Hi I upgraded MongoDB from 2.6.8 to 3.0.1 and genghis stopped to see my databases and collections. Do you know when Genghis will support this storage engine?

Thanks!

### CODE REVIEW

**Comment by bobthecow** [comment]
Hi @ttaranto. I haven't had a chance to upgrade to 3.0 yet and test, but there should be nothing fundamentally broken about the way Genghis and MongoDB communicate. I'll check it out, but if you need something working faster, try running the dev branch version. It uses newer driver versions, which might do the trick.

**Comment by bobthecow** [comment]
Also, I'm not entirely sure why this is a pull request, or what you're requesting :)

**Comment by stennie** [comment]
@ttaranto You need to update your MongoDB driver for support listing collections with alternative storage engines (and for full compatibility with MongoDB 3.0):
- [PHP 1.6+ driver](http://docs.mongodb.org/ecosystem/drivers/php/#mongodb-compatibility)
- [Ruby 1.12+ driver](http://docs.mongodb.org/ecosystem/drivers/ruby/#mongodb-compatibility)

**Comment by bobthecow** [comment]
Yep, with the latest driver versions everything seems to work on my local machine without changing Genghis at all.

**Comment by ttaranto** [comment]
Thank's all!

**Pull request closed without merging**
